import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { IsNotEmpty, IsOptional, IsString } from "class-validator";

export class SyncMobilePushTokenDto {
	@ApiProperty({
		description: "Unique device identifier generated by the mobile app",
		example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
	})
	@IsNotEmpty()
	@IsString()
	deviceId!: string;

	@ApiProperty({
		description: "Device type for the device being synchronized",
		enum: ["android", "ios", "web"],
		example: "android",
	})
	@IsNotEmpty()
	@IsString()
	deviceType!: string;

	@ApiPropertyOptional({
		description: "Human-friendly device name reported by the app",
		example: "Samsung Galaxy S25 Ultra",
	})
	@IsOptional()
	@IsString()
	deviceName?: string;

	@ApiProperty({
		description: "FCM token received after the user enables push notifications",
		example: "fcm_token_string_here",
	})
	@IsNotEmpty()
	@IsString()
	fcmToken!: string;
}
