import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsOptional, IsString } from "class-validator";

export class DeviceInfoDto {
	@ApiProperty({
		description: "Unique device identifier generated by mobile app",
		example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
	})
	@IsNotEmpty()
	@IsString()
	deviceId!: string;

	@ApiProperty({
		description:
			"FCM token for push notifications. Optional when OS notification permission has not been granted yet.",
		example: "fcm_token_string_here",
		required: false,
	})
	@IsOptional()
	@IsString()
	fcmToken?: string;

	@ApiProperty({
		description: "Device type",
		enum: ["android", "ios", "web"],
		example: "android",
	})
	@IsNotEmpty()
	@IsString()
	deviceType!: string;

	@ApiProperty({
		description: "Device name",
		example: "Samsung Galaxy S25 Ultra",
		required: false,
	})
	@IsOptional()
	@IsString()
	deviceName?: string;
}
