export const ACCOUNT_DELETION_DELAY_DAYS = 7;
export const ACCOUNT_DELETION_JOB_ID_PREFIX = "delete-user-account";
export const ACCOUNT_DELETION_BAN_REASON_PREFIX =
	"ACCOUNT_DELETION_PENDING_UNTIL:";
