import { relations, sql } from "drizzle-orm";
import {
	boolean,
	check,
	index,
	integer,
	jsonb,
	pgEnum,
	pgTable,
	text,
	timestamp,
	uniqueIndex,
	uuid,
} from "drizzle-orm/pg-core";
import { role } from "./roles";

export const sessionTypeEnum = pgEnum("session_type", [
	"mobile", // Enforced single session
	"web", // Multiple sessions allowed
]);

export const authActorTypeEnum = pgEnum("auth_actor_type", [
	"customer",
	"admin",
]);

export type AuthActorType = (typeof authActorTypeEnum.enumValues)[number];

const baseActorColumns = {
	id: uuid("id").primaryKey().default(sql`uuidv7()`),
	name: text("name").notNull(),
	email: text("email"),
	emailVerified: timestamp("email_verified", { withTimezone: true }),
	phone: text("phone"),
	phoneVerified: timestamp("phone_verified", { withTimezone: true }),
	image: text("image"),
	createdAt: timestamp("created_at", { withTimezone: true })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.notNull()
		.defaultNow()
		.$onUpdateFn(() => new Date()),
	banned: boolean("banned").default(false),
	banReason: text("ban_reason"),
} as const;

export const customers = pgTable(
	"customers",
	{
		...baseActorColumns,
		deletedAt: timestamp("deleted_at", { withTimezone: true }),
	},
	(table) => [
		uniqueIndex("customers_email_unique").on(table.email),
		uniqueIndex("customers_phone_unique").on(table.phone),
	],
);

export const adminUsers = pgTable(
	"admin_users",
	{
		...baseActorColumns,
		roleId: integer("role_id").references(() => role.id, {
			onDelete: "set null",
		}),
	},
	(table) => [
		uniqueIndex("admin_users_email_unique").on(table.email),
		uniqueIndex("admin_users_phone_unique").on(table.phone),
	],
);

export const userDevice = pgTable(
	"user_device",
	{
		id: uuid("id").primaryKey().default(sql`uuidv7()`),
		customerId: uuid("customer_id")
			.notNull()
			.references(() => customers.id, { onDelete: "cascade" }),

		// Hardware/Installation IDs
		deviceId: text("device_id").notNull(), // The Unique ID generated by the Mobile App
		fcmToken: text("fcm_token"), // Nullable (Permission might be revoked)

		deviceType: text("device_type").notNull(), // 'android', 'ios', 'web'
		deviceName: text("device_name"), // e.g. 'iPhone 15 Pro'

		isActive: boolean("is_active").default(true).notNull(),
		lastActiveAt: timestamp("last_active_at", { withTimezone: true })
			.defaultNow()
			.notNull(),
		createdAt: timestamp("created_at", { withTimezone: true })
			.defaultNow()
			.notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.defaultNow()
			.notNull()
			.$onUpdateFn(() => new Date()),
	},
	(table) => [
		index("user_device_lookup_idx").on(table.customerId, table.deviceId),
	],
);

export const customerSessions = pgTable(
	"customer_sessions",
	{
		id: uuid("id").primaryKey().default(sql`uuidv7()`),
		customerId: uuid("customer_id")
			.notNull()
			.references(() => customers.id, { onDelete: "cascade" }),
		token: text("token").notNull().unique(),
		expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
		type: sessionTypeEnum("type").default("web").notNull(),
		userDeviceId: uuid("user_device_id").references(() => userDevice.id, {
			onDelete: "set null",
		}),
		ipAddress: text("ip_address"),
		userAgent: text("user_agent"),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.notNull()
			.defaultNow()
			.$onUpdateFn(() => new Date()),
	},
	(table) => [
		index("customer_sessions_customer_id_idx").on(table.customerId),
		index("customer_sessions_device_id_idx").on(table.userDeviceId),
	],
);

export const adminSessions = pgTable(
	"admin_sessions",
	{
		id: uuid("id").primaryKey().default(sql`uuidv7()`),
		adminId: uuid("admin_id")
			.notNull()
			.references(() => adminUsers.id, { onDelete: "cascade" }),
		token: text("token").notNull().unique(),
		expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
		type: sessionTypeEnum("type").default("web").notNull(),
		ipAddress: text("ip_address"),
		userAgent: text("user_agent"),
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.notNull()
			.defaultNow()
			.$onUpdateFn(() => new Date()),
	},
	(table) => [index("admin_sessions_admin_id_idx").on(table.adminId)],
);

export const account = pgTable(
	"account",
	{
		id: uuid("id").primaryKey().default(sql`uuidv7()`),
		accountId: text("account_id").notNull(),
		providerId: text("provider_id").notNull(),
		actorType: authActorTypeEnum("actor_type").notNull(),
		customerId: uuid("customer_id").references(() => customers.id, {
			onDelete: "cascade",
		}),
		adminId: uuid("admin_id").references(() => adminUsers.id, {
			onDelete: "cascade",
		}),
		accessToken: text("access_token"),
		refreshToken: text("refresh_token"),
		idToken: text("id_token"),
		accessTokenExpiresAt: timestamp("access_token_expires_at", {
			withTimezone: true,
		}),
		refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
			withTimezone: true,
		}),
		scope: text("scope"),
		password: text("password"),
		createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.notNull()
			.$onUpdateFn(() => new Date()),
	},
	(table) => [
		check(
			"account_exactly_one_actor",
			sql`num_nonnulls(${table.customerId}, ${table.adminId}) = 1`,
		),
		index("account_customer_id_idx").on(table.actorType, table.customerId),
		index("account_admin_id_idx").on(table.actorType, table.adminId),
	],
);

export const verificationPurposeEnum = pgEnum("verification_purpose", [
	"email_verification",
	"password_reset",
	"phone_verification",
	"phone_login",
	"phone_registration",
]);

export const verificationChannelEnum = pgEnum("verification_channel", [
	"email",
	"sms",
]);

export type VerificationPurpose =
	(typeof verificationPurposeEnum.enumValues)[number];
export type VerificationChannel =
	(typeof verificationChannelEnum.enumValues)[number];

export interface VerificationMetadata {
	requestContext?: {
		ip?: string | null;
		userAgent?: string | null;
	};
	[key: string]: unknown;
}

export const verification = pgTable(
	"verification",
	{
		id: uuid("id").primaryKey().default(sql`uuidv7()`),
		identifier: text("identifier").notNull(),
		target: text("target").notNull(),
		purpose: verificationPurposeEnum("purpose").notNull(),
		channel: verificationChannelEnum("channel").notNull(),
		tokenHash: text("token_hash").notNull(),
		otpHash: text("otp_hash"),
		expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
		consumedAt: timestamp("consumed_at", { withTimezone: true }),
		metadata: jsonb("metadata").$type<VerificationMetadata | null>(),
		attempts: integer("attempts").notNull().default(0),
		maxAttempts: integer("max_attempts").notNull().default(5),
		createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
	},
	(table) => [
		index("verification_identifier_purpose_idx").on(
			table.identifier,
			table.purpose,
		),
		index("verification_target_purpose_idx").on(table.target, table.purpose),
		index("verification_expires_at_idx").on(table.expiresAt),
	],
);

// Relations
export const customersRelations = relations(customers, ({ many, one }) => ({
	devices: many(userDevice),
	sessions: many(customerSessions),
	account: one(account, {
		fields: [customers.id],
		references: [account.customerId],
	}),
}));

export const adminUsersRelations = relations(adminUsers, ({ many, one }) => ({
	role: one(role, {
		fields: [adminUsers.roleId],
		references: [role.id],
	}),
	sessions: many(adminSessions),
	account: one(account, {
		fields: [adminUsers.id],
		references: [account.adminId],
	}),
}));

export const accountRelations = relations(account, ({ one }) => ({
	customer: one(customers, {
		fields: [account.customerId],
		references: [customers.id],
	}),
	admin: one(adminUsers, {
		fields: [account.adminId],
		references: [adminUsers.id],
	}),
}));

export const customerSessionRelations = relations(
	customerSessions,
	({ one }) => ({
		device: one(userDevice, {
			fields: [customerSessions.userDeviceId],
			references: [userDevice.id],
		}),
		customer: one(customers, {
			fields: [customerSessions.customerId],
			references: [customers.id],
		}),
	}),
);

export const adminSessionRelations = relations(adminSessions, ({ one }) => ({
	admin: one(adminUsers, {
		fields: [adminSessions.adminId],
		references: [adminUsers.id],
	}),
}));

export const userDeviceRelations = relations(userDevice, ({ one, many }) => ({
	customer: one(customers, {
		fields: [userDevice.customerId],
		references: [customers.id],
	}),
	sessions: many(customerSessions),
}));
