name: bullhouse

services:
  postgres:
    image: postgres:18
    container_name: bullhouse-postgres
    environment:
      POSTGRES_DB: bullhouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bullhouse_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  bullhouse_postgres_data:
